version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3019:3019"
    environment:
      - PORT=3019
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=attendance_db
      - DB_PASSWORD=admin123
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "8133:80"
    networks:
      - app-network

  hr_page:
    build: ./Hr_page
    ports:
      - "8134:80"
    networks:
      - app-network

  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5447:5432"
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:

